import { ClerkProvider } from '@clerk/nextjs';
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Turborepo',
	description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
	return (
		<ClerkProvider>
			<html lang="en" data-theme="dark">
				<body className={inter.className}>
					{children}
					<SpeedInsights />
					<Analytics />
				</body>
			</html>
		</ClerkProvider>
	);
}
